# Generated by Django 4.2.2 on 2023-07-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='condition',
            field=models.CharField(choices=[('clearsky', 'Clear sky'), ('cloudy', 'Cloudy'), ('fair', 'Fair'), ('fog', 'Fog'), ('heavyrain', 'Heavy Rain'), ('heavyrainandthunder', 'Heavy Rain and Thunder'), ('heavyrainshowers', 'Heavy Rain Showers'), ('heavyrainshowersandthunder', 'Heavy Rain Showers and Thunder'), ('heavysleet', 'Heavy Sleet'), ('heavysleetandthunder', 'Heavy Sleet and Thunder'), ('heavysleetshowers', 'Heavy Sleet Showers'), ('heavysleetshowersandthunder', 'Heavy Sleet Showers and Thunder'), ('heavysnow', 'Heavy Snow'), ('heavysnowandthunder', 'Heavy Snow and Thunder'), ('heavysnowshowers', 'Heavy Snow Showers'), ('heavysnowshowersandthunder', 'Heavy Snow Showers and Thunder'), ('lightrain', 'Light Rain'), ('lightrainandthunder', 'Light Rain and Thunder'), ('lightrainshowers', 'Light Rain Showers'), ('lightrainshowersandthunder', 'Light Rain Showers and Thunder'), ('lightsleet', 'Light Sleet'), ('lightsleetandthunder', 'Light Sleet and Thunder'), ('lightsleetshowers', 'Light Sleet Showers'), ('lightsleetshowersandthunder', 'Light Sleet Showers and Thunder'), ('lightsnowshowersandthunder', 'Light Snow Showers and Thunder'), ('partlycloudy', 'Partly Cloudy'), ('rain', 'Rain'), ('rainandthunder', 'Rain and Thunder'), ('rainshowers', 'Rain showers'), ('rainshowersandthunder', 'Rain Showes and Thunder'), ('sleet', 'Sleet'), ('sleetandthunder', 'Sleet and Thunder'), ('sleetshowers', 'Sleet Showers'), ('sleetshowersandthunder', 'Sleet Showes and Thunder'), ('snow', 'Snow'), ('snowandthunder', 'Snow and Thunder'), ('snowshowers', 'Snow Showers'), ('snowshowersandthunder', 'Snow Showers and Thunder')], help_text='E.g Light Showers', null=True, verbose_name='General Weather Condition'),
        ),
        migrations.DeleteModel(
            name='ConditionCategory',
        ),
    ]
