# Generated by Django 4.2.3 on 2023-07-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0002_remove_forecast_max_temp_remove_forecast_min_temp_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together={('city', 'forecast_date', 'effective_period')},
        ),
    ]
