# Generated by Django 4.2.2 on 2023-07-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0003_alter_forecast_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdataparameters',
            name='parameter_type',
            field=models.CharField(choices=[('text', 'Text'), ('numeric', 'Number'), ('time', 'Time')], default='text', max_length=100, verbose_name='Parameter Type'),
        ),
        migrations.AlterField(
            model_name='forecastdataparameters',
            name='parameter',
            field=models.CharField(choices=[('air_temperature_max', 'Maximum Air Temperature'), ('air_temperature_min', 'Minimum Air Temperature'), ('air_temperature', 'Air Temperature'), ('dew_point_temperature', 'Dew Point Temperature'), ('precipitation_amount', 'Precipitation Amount'), ('air_pressure_at_sea_level', 'Air Pressure (Sea level)'), ('wind_speed', 'Wind Speed'), ('wind_from_direction', 'Wind Direction'), ('relative_humidity', 'Relative Humidity'), ('sunrise', 'Sunrise'), ('sunset', 'Sunrise'), ('moonrise', 'Moonrise'), ('moonset', 'Moonset')], max_length=100, unique=True, verbose_name='Parameter'),
        ),
    ]
