# Generated by Django 4.2.2 on 2023-07-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0004_forecastdataparameters_parameter_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdataparameters',
            name='parameter',
            field=models.CharField(choices=[('air_temperature_max', 'Maximum Air Temperature'), ('air_temperature_min', 'Minimum Air Temperature'), ('air_temperature', 'Air Temperature'), ('dew_point_temperature', 'Dew Point Temperature'), ('precipitation_amount', 'Precipitation Amount'), ('air_pressure_at_sea_level', 'Air Pressure (Sea level)'), ('wind_speed', 'Wind Speed'), ('wind_from_direction', 'Wind Direction'), ('relative_humidity', 'Relative Humidity'), ('sunrise', 'Sunrise'), ('sunset', 'Sunset'), ('moonrise', 'Moonrise'), ('moonset', 'Moonset')], max_length=100, unique=True, verbose_name='Parameter'),
        ),
    ]
