# Generated by Django 4.2.2 on 2023-07-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0005_alter_forecast_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together={('city', 'forecast_date')},
        ),
    ]
