# Generated by Django 4.2.2 on 2023-08-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0006_alter_forecastsetting_enable_auto_forecast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastsetting',
            name='temp_units',
        ),
        migrations.RemoveField(
            model_name='forecastsetting',
            name='wind_units',
        ),
        migrations.AddField(
            model_name='forecastdataparameters',
            name='parameter_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit of measurement'),
        ),
        migrations.AddField(
            model_name='forecastsetting',
            name='default_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forecastmanager.city', verbose_name='Default City'),
        ),
    ]
