# Generated by Django 4.2.2 on 2023-08-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0008_alter_forecastdataparameters_parameter_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdataparameters',
            name='parameter_unit',
            field=models.CharField(blank=True, default=' ', help_text='e.g °C, %, mm, hPa, etc ', max_length=100, null=True, verbose_name='Unit of measurement'),
        ),
    ]
