# Generated by Django 4.2.2 on 2023-07-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('forecastmanager', '0008_alter_forecast_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='ForecastSetting',
        ),
    ]
