# Generated by Django 4.2.2 on 2023-07-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0009_rename_setting_forecastsetting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together=set(),
        ),
    ]
