# Generated by Django 4.2.2 on 2023-09-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0009_alter_forecastdataparameters_parameter_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdataparameters',
            name='parameter_type',
            field=models.CharField(choices=[('numeric', 'Number'), ('time', 'Time'), ('text', 'Text')], default='numeric', max_length=100, verbose_name='Parameter Type'),
        ),
        migrations.AlterField(
            model_name='forecastdataparameters',
            name='parameter_unit',
            field=models.CharField(blank=True, help_text='e.g °C, %, mm, hPa, etc ', max_length=100, null=True, verbose_name='Unit of measurement'),
        ),
        migrations.AlterField(
            model_name='forecastsetting',
            name='default_city',
            field=models.ForeignKey(blank=True, help_text='City will appear as first in homepage city forecasts', null=True, on_delete=django.db.models.deletion.CASCADE, to='forecastmanager.city', verbose_name='Default City'),
        ),
    ]
