# Generated by Django 4.2.2 on 2023-07-04 12:17

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0010_alter_forecast_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(verbose_name='Forecast Date')),
                ('forecast_desc', wagtail.fields.RichTextField(verbose_name='Weather Forecast Description')),
                ('summary_date', models.DateField(verbose_name='Forecast Date')),
                ('summary_desc', wagtail.fields.RichTextField(verbose_name='Weather Summary Description')),
                ('extremes', wagtail.fields.StreamField([('extremes', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('measurements', wagtail.blocks.StreamBlock([('measurements', wagtail.blocks.StructBlock([('station_name', wagtail.blocks.CharBlock(required=True)), ('extreme_val', wagtail.blocks.FloatBlock(required=True))]))]))]))], use_json_field=True)),
            ],
        ),
    ]
