# Generated by Django 4.2.2 on 2023-09-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0010_alter_forecastdataparameters_parameter_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastperiod',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='forecastperiod',
            unique_together={('whole_day', 'forecast_effective_time')},
        ),
    ]
