# Generated by Django 4.2.2 on 2023-07-04 12:25

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0011_dailyweather'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyweather',
            name='extreme_date',
            field=models.DateField(null=True, verbose_name='Extreme Date'),
        ),
        migrations.AlterField(
            model_name='dailyweather',
            name='extremes',
            field=wagtail.fields.StreamField([('extremes', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('measurements', wagtail.blocks.StreamBlock([('measurements', wagtail.blocks.StructBlock([('station_name', wagtail.blocks.CharBlock(required=True)), ('extreme_value', wagtail.blocks.FloatBlock(required=True))]))]))]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='dailyweather',
            name='summary_date',
            field=models.DateField(verbose_name='Summary Date'),
        ),
    ]
