# Generated by Django 4.2.2 on 2023-09-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0011_alter_forecastperiod_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastperiod',
            name='forecast_effective_time',
            field=models.TimeField(verbose_name='Forecast Effective Time'),
        ),
    ]
