# Generated by Django 4.2.3 on 2024-03-08 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0013_alter_city_options_alter_forecast_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastsetting',
            name='default_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forecastmanager.city', verbose_name='Default City'),
        ),
    ]
