# Generated by Django 4.2.2 on 2023-07-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0013_alter_dailyweather_extreme_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyweather',
            name='issued_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
