# Generated by Django 4.2.3 on 2024-04-15 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0021_forecastsetting_weather_reports_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdataparameters',
            name='parameter_type',
            field=models.CharField(choices=[('numeric', 'Number'), ('text', 'Text')], default='numeric', max_length=100, verbose_name='Parameter Type'),
        ),
        migrations.AlterField(
            model_name='forecastsetting',
            name='default_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecastmanager.city', verbose_name='Default City'),
        ),
    ]
