# Generated by Django 4.2.3 on 2024-04-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0022_alter_forecastdataparameters_parameter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdataparameters',
            name='use_known_parameters',
            field=models.BooleanField(default=True, verbose_name='Use known parameters'),
        ),
    ]
