# Generated by Django 4.2.3 on 2024-04-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0023_forecastdataparameters_use_known_parameters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast',
            options={'ordering': ['-forecast_date', 'effective_period'], 'verbose_name': 'Forecast', 'verbose_name_plural': 'Forecasts'},
        ),
        migrations.AlterField(
            model_name='forecastdataparameters',
            name='parameter',
            field=models.CharField(max_length=100, unique=True, verbose_name='Parameter'),
        ),
        migrations.AlterField(
            model_name='forecastdataparameters',
            name='use_known_parameters',
            field=models.BooleanField(default=True, verbose_name='Use predefined parameters'),
        ),
    ]
