# Generated by Django 4.2.7 on 2024-06-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0024_alter_forecast_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast',
            options={'ordering': ['forecast_date', 'effective_period'], 'verbose_name': 'Forecast', 'verbose_name_plural': 'Forecasts'},
        ),
        migrations.AlterModelOptions(
            name='forecastperiod',
            options={'ordering': ['forecast_effective_time']},
        ),
    ]
