# Generated by Django 4.2.3 on 2024-07-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0026_alter_forecastperiod_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdataparameters',
            name='show_on_home_widget',
            field=models.BooleanField(default=True, verbose_name='Show on Home Widget'),
        ),
    ]
