# Generated by Django 4.2.3 on 2024-07-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0027_forecastdataparameters_show_on_home_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastsetting',
            name='show_conditions_label_on_widget',
            field=models.BooleanField(default=True, verbose_name='Show conditions label on widget'),
        ),
    ]
