# Generated by Django 5.2.1 on 2025-07-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0028_forecastsetting_show_conditions_label_on_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastsetting',
            name='use_period_labels',
            field=models.BooleanField(default=False, verbose_name='Use Period Labels inplace of forecast time'),
        ),
    ]
