# Generated by Django 5.2.12 on 2026-06-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastmanager', '0031_forecast_status_and_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastsetting',
            name='auto_publish_forecasts',
            field=models.BooleanField(default=True, help_text='When off, automated forecasts are saved as drafts for a forecaster to review and publish. When on, they are published immediately.', verbose_name='Auto-publish automated forecasts'),
        ),
    ]
